workflows:
  nexa-android:
    name: NEXA Android APK
    max_build_duration: 60
    instance_type: linux
    environment:
      flutter: stable
    scripts:
      - name: Dependance Flutter
        script: flutter packages pub get
      - name: Build APK release
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - destinbyoto@gmail.com
